class Doctor {
  final int id;
  final String name;
  final double rating;
  final String about;
  final int experience;
  final List<String> degrees;
  final int numberOfPatients;
  final bool isActive;
  final String speciality;

  Doctor({
    required this.id,
    required this.name,
    required this.rating,
    required this.about,
    required this.experience,
    required this.degrees,
    required this.numberOfPatients,
    required this.isActive,
    required this.speciality,

  });
}

List<Doctor> Cardiologist= [
Doctor(
id: 1,
name: 'Dr. John Smith',
rating: 4.5,
about: 'Dr. John Smith is a highly experienced cardiologist with over 20 years of experience in the field. He has treated numerous patients with various heart conditions and is known for his compassionate and patient-centered approach to care.',
experience: 20,
degrees: ['MD', 'PhD'],
numberOfPatients: 500,
isActive: true,
speciality: 'Cardiology',
),
Doctor(
id: 2,
name: 'Dr. Jane Doe',
rating: 4.8,
about: 'Dr. Jane Doe is a board-certified cardiologist with a special interest in heart disease prevention and management. She has published several research papers on the topic and is a sought-after speaker at medical conferences.',
experience: 15,
degrees: ['MD', 'MPH'],
numberOfPatients: 300,
isActive: true,
speciality: 'Cardiology',
),
Doctor(
id: 3,
name: 'Dr. David Lee',
rating: 4.2,
about: 'Dr. David Lee is an interventional cardiologist with expertise in complex coronary interventions and structural heart disease treatments. He has performed hundreds of successful procedures and is highly respected among his colleagues.',
experience: 12,
degrees: ['MD', 'FACC'],
numberOfPatients: 250,
isActive: true,
speciality: 'Cardiology',
),
Doctor(
id: 4,
name: 'Dr. Sarah Kim',
rating: 4.6,
about: 'Dr. Sarah Kim is a cardiologist with a focus on heart failure and transplant. She has extensive experience in managing advanced heart failure patients and has helped many patients improve their quality of life.',
experience: 18,
degrees: ['MD', 'FACC'],
numberOfPatients: 400,
isActive: true,
speciality: 'Cardiology',
),
Doctor(
id: 5,
name: 'Dr. Michael Chen',
rating: 4.3,
about: 'Dr. Michael Chen is a non-invasive cardiologist with expertise in echocardiography and cardiac imaging. He has a special interest in valvular heart disease and has published several papers on the topic.',
experience: 10,
degrees: ['MD', 'FACC'],
numberOfPatients: 200,
isActive: true,
speciality: 'Cardiology',
),
Doctor(
id: 6,
name: 'Dr. Elizabeth Brown',
rating: 4.1,
about: 'Dr. Elizabeth Brown is a cardiologist with a focus on women\'s heart health. She is passionate about educating women on the importance of heart disease prevention and has developed several educational programs for the community.',
experience: 8,
degrees: ['MD', 'FACC'],
numberOfPatients: 150,
isActive: true,
speciality: 'Cardiology',
),
Doctor(
id: 7,
name: 'Dr. Steven Park',
rating: 4.4,
about: 'Dr. Steven Park is a cardiac electrophysiologist with expertise in arrhythmia management and device therapy. He has performed numerous successful procedures and is highly regarded in his field.',
experience: 14,
degrees: ['MD', 'FHRS'],
numberOfPatients: 300,
isActive: true,
speciality: 'Cardiology',
),
Doctor(
id: 8,
name: 'Dr. Karen Lee',
rating: 4.7,
about: 'Dr. Karen Lee is a non-invasive cardiologist with a special interest in preventive cardiology. She has developed several programs to help patients reduce their risk of heart disease and has helped many patients make positive lifestyle changes.',
experience: 16,
degrees: ['MD', 'FACC', 'FAHA'],
numberOfPatients: 350,
isActive: true,
speciality: 'Cardiology',
),
Doctor(
id: 9,
name: 'Dr. Robert Johnson',
rating: 4.0,
about: 'Dr. Robert Johnson is a cardiologist with expertise in interventional cardiology and peripheral vascular disease. He has performed numerous successful procedures and is highly regarded among his peers.',
experience: 11,
degrees: ['MD', 'FACC'],
numberOfPatients: 200,
isActive: true,
speciality: 'Cardiology',
),
];
List<Doctor> neurologist=[
Doctor(
id: 1,
name: "Dr. Jane Doe",
rating: 4.8,
about: "Dr. Jane Doe is a board-certified neurologist with over 10 years of experience in diagnosing and treating neurological disorders.",
experience: 10,
degrees: ["MD", "PhD"],
numberOfPatients: 500,
isActive: true,
speciality: "Neurology",
),
Doctor(
id: 2,
name: "Dr. John Smith",
rating: 4.5,
about: "Dr. John Smith is a board-certified cardiologist with over 15 years of experience in diagnosing and treating heart conditions.",
experience: 15,
degrees: ["MD"],
numberOfPatients: 700,
isActive: false,
speciality: "Cardiology",
),
Doctor(
id: 3,
name: "Dr. Sarah Lee",
rating: 4.2,
about: "Dr. Sarah Lee is a board-certified dermatologist with over 5 years of experience in diagnosing and treating skin conditions.",
experience: 5,
degrees: ["MD"],
numberOfPatients: 300,
isActive: true,
speciality: "Dermatology",
),
Doctor(
id: 4,
name: "Dr. Michael Chen",
rating: 4.9,
about: "Dr. Michael Chen is a board-certified pediatrician with over 20 years of experience in providing medical care to children.",
experience: 20,
degrees: ["MD"],
numberOfPatients: 1000,
isActive: true,
speciality: "Pediatrics",
),
Doctor(
id: 5,
name: "Dr. Lisa Kim",
rating: 4.6,
about: "Dr. Lisa Kim is a board-certified gynecologist with over 8 years of experience in providing women's health care.",
experience: 8,
degrees: ["MD"],
numberOfPatients: 400,
isActive: true,
speciality: "Gynecology",
),
Doctor(
id: 6,
name: "Dr. David Wong",
rating: 4.4,
about: "Dr. David Wong is a board-certified urologist with over 12 years of experience in diagnosing and treating urinary tract and reproductive system disorders.",
experience: 12,
degrees: ["MD", "PhD"],
numberOfPatients: 600,
isActive: false,
speciality: "Urology",
),
Doctor(
id: 7,
name: "Dr. Rachel Park",
rating: 4.7,
about: "Dr. Rachel Park is a board-certified psychiatrist with over 7 years of experience in diagnosing and treating mental health disorders.",
experience: 7,
degrees: ["MD"],
numberOfPatients: 200,
isActive: true,
speciality: "Psychiatry",
),
Doctor(
id: 8,
name: "Dr. William Brown",
rating: 4.3,
about: "Dr. William Brown is a board-certified orthopedic surgeon with over 10 years of experience in diagnosing and treating musculoskeletal conditions.",
experience: 10,
degrees: ["MD"],
numberOfPatients: 450,
isActive: true,
speciality: "Orthopedics",
),
Doctor(
id: 9,
name: "Dr. Emily Davis",
rating: 4.1,
about: "Dr. Emily Davis is a board-certified endocrinologist with over 6 years of experience in diagnosing and treating hormonal imbalances.",
experience: 6,
degrees: ["MD"],
numberOfPatients: 350,
isActive: false,
speciality: "Endocrinology",
),
Doctor(
id: 10,
name: "Dr. James Johnson",
rating: 4.0,
about: "Dr. James Johnson is a board-certified gastroenterologist with over 9 years of experience in diagnosing and treating digestive .",
experience: 6,
degrees: ["MD"],
numberOfPatients: 350,
isActive: false,
speciality: "Endocrinology",),
];

List<Doctor> Dentist=[
Doctor(
id: 1,
name: "Dr. Emily Wong",
rating: 4.8,
about: "Dr. Emily Wong is a board-certified dentist with over 10 years of experience providing general and cosmetic dental services.",
experience: 10,
degrees: ["DDS"],
numberOfPatients: 800,
isActive: true,
speciality: "Dentistry",
),
Doctor(
id: 2,
name: "Dr. Michael Lee",
rating: 4.5,
about: "Dr. Michael Lee is a board-certified dentist with over 15 years of experience providing dental care for families and children.",
experience: 15,
degrees: ["DDS"],
numberOfPatients: 700,
isActive: false,
speciality: "Pediatric Dentistry",
),
Doctor(
id: 3,
name: "Dr. Sophia Kim",
rating: 4.2,
about: "Dr. Sophia Kim is a board-certified dentist with over 5 years of experience providing orthodontic services to patients of all ages.",
experience: 5,
degrees: ["DDS"],
numberOfPatients: 300,
isActive: true,
speciality: "Orthodontics",
),
Doctor(
id: 4,
name: "Dr. David Chen",
rating: 4.9,
about: "Dr. David Chen is a board-certified dentist with over 20 years of experience providing high-quality dental care to patients.",
experience: 20,
degrees: ["DDS"],
numberOfPatients: 1000,
isActive: true,
speciality: "General Dentistry",
),
Doctor(
id: 5,
name: "Dr. Lisa Park",
rating: 4.6,
about: "Dr. Lisa Park is a board-certified dentist with over 8 years of experience providing cosmetic dental services, including teeth whitening and veneers.",
experience: 8,
degrees: ["DDS"],
numberOfPatients: 400,
isActive: true,
speciality: "Cosmetic Dentistry",
),
Doctor(
id: 6,
name: "Dr. William Brown",
rating: 4.4,
about: "Dr. William Brown is a board-certified dentist with over 12 years of experience providing restorative dental services, including crowns and bridges.",
experience: 12,
degrees: ["DDS"],
numberOfPatients: 600,
isActive: false,
speciality: "Restorative Dentistry",
),
Doctor(
id: 7,
name: "Dr. Rachel Johnson",
rating: 4.7,
about: "Dr. Rachel Johnson is a board-certified dentist with over 7 years of experience providing dental care for patients with special needs.",
experience: 7,
degrees: ["DDS"],
numberOfPatients: 200,
isActive: true,
speciality: "Special Needs Dentistry",
),
Doctor(
id: 8,
name: "Dr. James Davis",
rating: 4.3,
about: "Dr. James Davis is a board-certified dentist with over 10 years of experience providing periodontal services, including gum disease treatment and dental implants.",
experience: 10,
degrees: ["DDS"],
numberOfPatients: 450,
isActive: true,
speciality: "Periodontics",
),
Doctor(
id: 9,
name: "Dr. Emily Kim",
rating: 4.1,
about: "Dr. Emily Kim is a board-certified dentist with over 6 years of experience providing dental care for patients with TMJ disorders.",
experience: 6,
degrees: ["DDS"],
numberOfPatients: 350,
isActive: false,
speciality: "TMJ Dentistry",
),
Doctor(
id: 10,
name: "Dr. John Smith",
rating: 4.0,
about: "Dr. John Smith is a board-certified dentist with over 9 years of experience providing dental care for seniors and",
experience: 6,
degrees: ["DDS"],
numberOfPatients: 350,
isActive: false,
speciality: "TMJ Dentistry",),
];

List<Doctor> ENT=[
Doctor(
id: 1,
name: "Dr. Emily Wong",
rating: 4.8,
about: "Dr. Emily Wong is a board-certified ENT doctor with over 10 years of experience in diagnosing and treating ear, nose, and throat conditions.",
experience: 10,
degrees: ["MD"],
numberOfPatients: 800,
isActive: true,
speciality: "ENT",
),
Doctor(
id: 2,
name: "Dr. Michael Lee",
rating: 4.5,
about: "Dr. Michael Lee is a board-certified ENT doctor with over 15 years of experience in diagnosing and treating sinus and allergy conditions.",
experience: 15,
degrees: ["MD"],
numberOfPatients: 700,
isActive: false,
speciality: "ENT",
),
Doctor(
id: 3,
name: "Dr. Sophia Kim",
rating: 4.2,
about: "Dr. Sophia Kim is a board-certified ENT doctor with over 5 years of experience in diagnosing and treating hearing and balance disorders.",
experience: 5,
degrees: ["MD"],
numberOfPatients: 300,
isActive: true,
speciality: "ENT",
),
Doctor(
id: 4,
name: "Dr. David Chen",
rating: 4.9,
about: "Dr. David Chen is a board-certified ENT doctor with over 20 years of experience in diagnosing and treating voice and swallowing disorders.",
experience: 20,
degrees: ["MD"],
numberOfPatients: 1000,
isActive: true,
speciality: "ENT",
),
Doctor(
id: 5,
name: "Dr. Lisa Park",
rating: 4.6,
about: "Dr. Lisa Park is a board-certified ENT doctor with over 8 years of experience in diagnosing and treating pediatric ear, nose, and throat conditions.",
experience: 8,
degrees: ["MD"],
numberOfPatients: 400,
isActive: true,
speciality: "Pediatric ENT",
),
Doctor(
id: 6,
name: "Dr. William Brown",
rating: 4.4,
about: "Dr. William Brown is a board-certified ENT doctor with over 12 years of experience in diagnosing and treating head and neck tumors.",
experience: 12,
degrees: ["MD"],
numberOfPatients: 600,
isActive: false,
speciality: "ENT Oncology",
),
Doctor(
id: 7,
name: "Dr. Rachel Johnson",
rating: 4.7,
about: "Dr. Rachel Johnson is a board-certified ENT doctor with over 7 years of experience in diagnosing and treating snoring and sleep apnea.",
experience: 7,
degrees: ["MD"],
numberOfPatients: 200,
isActive: true,
speciality: "Sleep Medicine",
),
Doctor(
id: 8,
name: "Dr. James Davis",
rating: 4.3,
about: "Dr. James Davis is a board-certified ENT doctor with over 10 years of experience in diagnosing and treating tinnitus and vertigo.",
experience: 10,
degrees: ["MD"],
numberOfPatients: 450,
isActive: true,
speciality: "ENT",
),
Doctor(
id: 9,
name: "Dr. Emily Kim",
rating: 4.1,
about: "Dr. Emily Kim is a board-certified ENT doctor with over 6 years of experience in diagnosing and treating nasal polyps and sinusitis.",
experience: 6,
degrees: ["MD"],
numberOfPatients: 350,
isActive: false,
speciality: "ENT",
),
Doctor(
id: 10,
name: "Dr. John Smith",
rating: 4.0,
about: "Dr. John Smith is a board-certified ENT doctor with over 9 years of experience in diagnosing and",
experience: 6,
degrees: ["MD"],
numberOfPatients: 350,
isActive: false,
speciality: "ENT",),
];
